version: '3'

services:
  node-gif:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-gif
    container_name: node-gif
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "80:80"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: /home/node/app/node_modules/.bin/nodemon src/index.js

volumes:
  node_modules: